{{- range tuple "obj-01" "init" "init-extras" "rest-02-data-tool" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: archive-datagenerator-static-{{.}}-configmap
  namespace: {{$.Release.Namespace}}
data:
{{- $path := printf "config/%s/*" . }}
{{ (tpl ($.Files.Glob $path).AsConfig $) | indent 2 }}
{{end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: archive-datagenerator-static-entrypoint
  namespace: {{.Release.Namespace}}
data:
{{ (tpl (.Files.Glob "entrypoint/entrypoint.sh").AsConfig .) | indent 2 }}
