---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-journal
  namespace: {{.Release.Namespace}}
  labels:
    app: archive-journal
spec:
  selector:
    matchLabels:
      app: archive-journal
  template:
    metadata:
      labels:
        app: archive-journal
    spec:
      volumes:
        - name: archive-rest-01-configmap
          configMap:
            name: archive-rest-01-configmap
        - name: archive-entrypoint
          configMap:
            name: archive-entrypoint
      hostname: archive-journal
      subdomain: tg
      containers:
        - name: archive-journal
          image: {{.Values.image.path}}:{{.Values.image.version}}
          volumeMounts:
            - mountPath: /config/
              name: archive-rest-01-configmap
            - mountPath: /entrypoint.sh
              name: archive-entrypoint
              subPath: entrypoint.sh
          tty: true
          resources:
            requests:
              cpu: "0.001m"
            limits:
              cpu: "{{.Values.resources.archive.journal.cpu}}"
          env:
          - name: IPA_DOMAIN
            value: {{.Values.ipa.domain}}
          - name: IPA_PASSWORD
            value: {{.Values.ipa.password}}
          readinessProbe:
            exec:
              command:
              - "/usr/bin/bash"
              - "-c"
              - "systemctl status rest-01 && journalctl -u rest-01 | grep \"Started Main\""
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 60
          securityContext:
            privileged: {{.Values.security.privileged}}
          lifecycle:
            preStop:
              exec:
                command: [ "/usr/bin/bash", "/scripts/shutdown.sh" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-journal-database
  namespace: {{.Release.Namespace}}
  labels:
    app: archive-journal-database
spec:
  selector:
    matchLabels:
      app: archive-journal-database
  template:
    metadata:
      labels:
        app: archive-journal-database
    spec:
      volumes:
        - name: archive-rest-01-database-configmap
          configMap:
            name: archive-rest-01-database-configmap
        - name: archive-entrypoint
          configMap:
            name: archive-entrypoint
      hostname: archive-journal-database
      subdomain: tg
      containers:
        - name: archive-journal-database
          image: {{.Values.image.database.path}}:{{.Values.image.database.version}}
          volumeMounts:
            - mountPath: /config
              name: archive-rest-01-database-configmap
            - mountPath: /entrypoint.sh
              name: archive-entrypoint
              subPath: entrypoint.sh
          tty: true
          resources:
            requests:
              cpu: "0.001m"
            limits:
              cpu: "{{.Values.resources.archive.catalogdatabase.cpu}}"
          env:
          - name: IPA_DOMAIN
            value: {{.Values.ipa.domain}}
          - name: IPA_PASSWORD
            value: {{.Values.ipa.password}}
          readinessProbe:
            exec:
              command:
              - "/usr/bin/bash"
              - "-c"
              - "mariadb <<< 'select 1'"
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 60
          securityContext:
            privileged: {{.Values.security.privileged}}
          lifecycle:
            preStop:
              exec:
                command: [ "/usr/bin/bash", "/scripts/shutdown.sh" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-catalog
  namespace: {{.Release.Namespace}}
  labels:
    app: archive-catalog
spec:
  selector:
    matchLabels:
      app: archive-catalog
  template:
    metadata:
      labels:
        app: archive-catalog
    spec:
      volumes:
        - name: archive-rest-02-backend-configmap
          configMap:
            name: archive-rest-02-backend-configmap
        - name: archive-entrypoint
          configMap:
            name: archive-entrypoint
      hostname: archive-catalog
      subdomain: tg
      containers:
        - name: archive-catalog
          image: {{.Values.image.path}}:{{.Values.image.version}}
          volumeMounts:
            - mountPath: /config/
              name: archive-rest-02-backend-configmap
            - mountPath: /entrypoint.sh
              name: archive-entrypoint
              subPath: entrypoint.sh
          tty: true
          resources:
            requests:
              cpu: "0.001m"
            limits:
              cpu: "{{.Values.resources.archive.catalog.cpu}}"
          env:
          - name: IPA_DOMAIN
            value: {{.Values.ipa.domain}}
          - name: IPA_PASSWORD
            value: {{.Values.ipa.password}}
          readinessProbe:
            exec:
              command:
              - "/usr/bin/bash"
              - "-c"
              - "systemctl status rest-02-backend && journalctl -u rest-02-backend | grep \"Started Main\""
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 60
          securityContext:
            privileged: {{.Values.security.privileged}}
          lifecycle:
            preStop:
              exec:
                command: [ "/usr/bin/bash", "/scripts/shutdown.sh" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-catalog-database
  namespace: {{.Release.Namespace}}
  labels:
    app: archive-catalog-database
spec:
  selector:
    matchLabels:
      app: archive-catalog-database
  template:
    metadata:
      labels:
        app: archive-catalog-database
    spec:
      volumes:
        - name: archive-rest-02-backend-database-configmap
          configMap:
            name: archive-rest-02-backend-database-configmap
        - name: archive-entrypoint
          configMap:
            name: archive-entrypoint
      hostname: archive-catalog-database
      subdomain: tg
      containers:
        - name: archive-catalog-database
          image: {{.Values.image.database.path}}:{{.Values.image.database.version}}
          volumeMounts:
            - mountPath: /config
              name: archive-rest-02-backend-database-configmap
            - mountPath: /entrypoint.sh
              name: archive-entrypoint
              subPath: entrypoint.sh
          tty: true
          resources:
            requests:
              cpu: "0.001m"
            limits:
              cpu: "{{.Values.resources.archive.catalogdatabase.cpu}}"
          env:
          - name: IPA_DOMAIN
            value: {{.Values.ipa.domain}}
          - name: IPA_PASSWORD
            value: {{.Values.ipa.password}}
          readinessProbe:
            exec:
              command:
              - "/usr/bin/bash"
              - "-c"
              - "mariadb <<< 'select 1'"
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 60
          securityContext:
            privileged: {{.Values.security.privileged}}
          lifecycle:
            preStop:
              exec:
                command: [ "/usr/bin/bash", "/scripts/shutdown.sh" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-s3
  namespace: {{.Release.Namespace}}
  labels:
    app: archive-s3
spec:
  selector:
    matchLabels:
      app: archive-s3
  template:
    metadata:
      labels:
        app: archive-s3
    spec:
      volumes:
        - name: archive-pth-05-configmap
          configMap:
            name: archive-pth-05-configmap
        - name: archive-bos-01-configmap
          configMap:
            name: archive-bos-01-configmap
        - name: archive-entrypoint
          configMap:
            name: archive-entrypoint
      hostname: archive-s3
      subdomain: tg
      containers:
        - name: archive-s3
          image: {{.Values.image.path}}:{{.Values.image.version}}
          volumeMounts:
            - mountPath: /config/pth-05/
              name: archive-pth-05-configmap
            - mountPath: /config/bos-01/
              name: archive-bos-01-configmap
            - mountPath: /entrypoint.sh
              name: archive-entrypoint
              subPath: entrypoint.sh
          tty: true
          resources:
            requests:
              cpu: "0.001m"
            limits:
              cpu: "{{.Values.resources.archive.s3.cpu}}"
          env:
          - name: IPA_DOMAIN
            value: {{.Values.ipa.domain}}
          - name: IPA_PASSWORD
            value: {{.Values.ipa.password}}
          readinessProbe:
            exec:
              command:
              - "/usr/bin/bash"
              - "-c"
              - "systemctl status bos_01 && systemctl status pth_05"
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 60
          securityContext:
            privileged: {{.Values.security.privileged}}
          lifecycle:
            preStop:
              exec:
                command: [ "/usr/bin/bash", "/scripts/shutdown.sh" ]
