---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ipa-configmap
  namespace: {{.Release.Namespace}}
data:
{{ (tpl (.Files.Glob "config/*").AsConfig .) | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ipa-entrypoint
  namespace: {{.Release.Namespace}}
data:
{{ (tpl (.Files.Glob "entrypoint/entrypoint*.sh").AsConfig .) | indent 2 }}
